"""Единый словарь военных классов для YOLO-World (88 классов).
ВАЖНО: при изменении списка НУЖНО заново экспортировать ONNX!"""

# ── Русские переводы классов (для отображения в GUI/HTML/JSON) ──
# Оригинальный MILITARY_CLASSES НЕ МЕНЯЕТСЯ — он нужен для YOLO.
CLASSES_RU = {
    # ── Бронетехника и авиация ──
    "tank": "танк",
    "tank turret in ground": "вкопанная башня",
    "dug-in artillery": "окопанная артиллерия",
    "armored vehicle": "бронемашина",
    "armored personnel carrier": "БТР",
    "vehicle with cage armor": "техника с решётчатой бронёй",
    "military truck": "военный грузовик",
    "military jeep": "военный джип",
    "tanker truck": "цистерна",
    "self-propelled artillery": "самоходная артиллерия",
    "multiple rocket launcher": "РСЗО",
    "anti-aircraft gun": "зенитное орудие",
    "howitzer": "гаубица",
    "missile launcher": "пусковая установка",
    "military helicopter": "военный вертолёт",
    "military aircraft": "военный самолёт",
    "quadcopter drone": "квадрокоптер",
    "military boat": "военный катер",
    "inflatable decoy": "надувная ложная цель",
    # ── Личный состав и активность ──
    "soldier": "солдат",
    "person in camouflage uniform": "человек в камуфляже",
    "armed person": "вооружённый человек",
    "person carrying rifle": "человек с винтовкой",
    "person with shovel": "человек с лопатой",
    "soldier digging trench": "солдат копает окоп",
    "group of soldiers": "группа солдат",
    # ── Вооружение, снаряжение, хозяйство ──
    "rifle": "винтовка",
    "machine gun": "пулемёт",
    "grenade launcher": "гранатомёт",
    "anti-tank missile": "противотанковая ракета",
    "ammunition box": "ящик с боеприпасами",
    "wooden crate": "деревянный ящик",
    "metal barrel": "металлическая бочка",
    "jerry can": "канистра",
    "portable generator": "переносной генератор",
    "field kitchen": "полевая кухня",
    "wooden pallet": "деревянный поддон",
    # ── Антенны, РЭБ, связь ──
    "military radio antenna": "военная радиоантенна",
    "radio mast": "радиомачта",
    "satellite dish": "спутниковая тарелка",
    "radar": "радар",
    "electronic warfare antenna": "антенна РЭБ",
    "communication antenna": "антенна связи",
    # ── Укрепления и заграждения ──
    "trench": "окоп",
    "bunker": "бункер",
    "dugout entrance": "вход в блиндаж",
    "foxhole": "окопчик",
    "barbed wire": "колючая проволока",
    "barbed wire coil": "моток колючей проволоки",
    "anti-tank obstacle": "противотанковое заграждение",
    "dragon teeth obstacle": "зубы дракона",
    "Czech hedgehog obstacle": "чешский ёж",
    "concrete block barricade": "бетонный блок",
    "gabion barrier": "габион",
    "sandbag wall": "мешки с песком",
    "checkpoint": "блокпост",
    "watchtower": "вышка",
    "earth berm": "земляной вал",
    "anti-tank ditch": "противотанковый ров",
    # ── Маскировка и укрытия ──
    "camouflage net": "маскировочная сеть",
    "camouflaged position": "замаскированная позиция",
    "vehicle under net": "техника под сетью",
    "covered vehicle": "укрытая техника",
    "military tent": "военная палатка",
    "medical tent": "медицинская палатка",
    "command tent": "командная палатка",
    "anti-drone net": "противодронная сеть",
    "drone protection cage": "защитная клетка от дронов",
    "metal grille armor": "металлическая решётка",
    "cut branches on ground": "срезанные ветки на земле",
    # ── СЛЕДЫ ПРИСУТСТВИЯ ──
    "plastic bottle": "пластиковая бутылка",
    "metal can": "металлическая банка",
    "food wrapper": "обёртка от еды",
    "discarded paper": "брошенная бумага",
    "cardboard box": "картонная коробка",
    "plastic bag": "пластиковый пакет",
    "garbage pile": "куча мусора",
    "campfire remains": "остатки костра",
    "smoke plume": "дым",
    "dust cloud": "облако пыли",
    "tire track": "след от шин",
    "footpath in grass": "тропинка в траве",
    "trampled vegetation": "вытоптанная растительность",
    "disturbed soil": "нарушенный грунт",
    "fresh dug dirt": "свежевырытая земля",
    "discarded clothing": "брошенная одежда",

    # ── НОВЫЕ КЛАССЫ v2 (переводы) ──
    "soldier in civilian clothing": "боец в гражданской одежде",
    "soldier lying prone": "лежащий солдат",
    "running soldier": "бегущий солдат",
    "soldier carrying military backpack": "солдат с рюкзаком",
    "combat medic with armband": "медик с повязкой",
    "wounded soldier": "раненый боец",
    "fallen body": "тело погибшего",
    "ghillie suit": "маскхалат (гили)",
    "military helmet": "военная каска",
    "body armor vest": "бронежилет",
    "tactical vest with pouches": "тактическая разгрузка",
    "military backpack": "военный рюкзак",
    "combat tourniquet": "тактический жгут",
    "rolled bandage": "скатка бинта",
    "bloody bandage": "окровавленный бинт",
    "first aid pouch IFAK": "армейская аптечка",
    "stretcher": "носилки",
    "battle rifle": "автоматическая винтовка",
    "carbine": "карабин",
    "submachine gun": "пистолет-пулемёт",
    "light machine gun": "ручной пулемёт",
    "general purpose machine gun": "единый пулемёт",
    "heavy machine gun": "крупнокалиберный пулемёт",
    "anti-materiel rifle": "крупнокалиберная снайперская винтовка",
    "suppressed rifle": "винтовка с глушителем",
    "underbarrel grenade launcher": "подствольный гранатомёт",
    "telescopic sight": "оптический прицел",
    "bipod": "сошки",
    "spent cartridge case": "стреляная гильза (стрелковая)",
    "pile of shell casings": "куча стреляных гильз",
    "spent artillery shell casing": "стреляная артиллерийская гильза",
    "pile of artillery shell casings": "куча артиллерийских гильз",
    "spent mortar round tail fin": "хвостовик миномётной мины",
    "ammunition magazine": "магазин патронный",
    "ammo belt": "патронная лента",
    "linked ammunition box": "короб с лентой",
    "ammunition crate": "ящик с боеприпасами",
    "artillery shell": "артиллерийский снаряд",
    "mortar round": "миномётная мина",
    "hand grenade": "ручная граната",
    "anti-tank mine": "противотанковая мина",
    "anti-personnel mine": "противопехотная мина",
    "directional fragmentation mine": "мина направленного действия (МОН-50)",
    "bounding mine": "прыгающая мина (ОЗМ-72)",
    "tripwire booby trap": "растяжка",
    "RPG-7 grenade launcher": "гранатомёт РПГ-7",
    "spent RPG launch tube": "стреляный тубус РПГ",
    "RPG-18 Mukha launcher": "РПГ-18 \"Муха\"",
    "RPG-26 launcher": "РПГ-26",
    "M72 LAW launcher": "M72 LAW",
    "AT4 disposable launcher": "AT4",
    "MRO-A Shmel thermobaric": "МРО-А \"Шмель\"",
    "anti-tank guided missile launcher": "ПТРК (пусковая)",
    "ATGM missile in container": "ПТУР в контейнере",
    "MANPADS": "ПЗРК",
    "FPV drone": "FPV-дрон",
    "fixed-wing drone": "дрон самолётного типа (\"крыло\")",
    "reconnaissance drone": "разведывательный дрон",
    "drone propeller": "пропеллер дрона",
    "drone wreckage": "обломки дрона",
    "fiber optic spool": "катушка оптоволокна",
    "thin glinting fiber optic cable": "оптоволоконная нить (блик)",
    "drone antenna": "антенна дрона",
    "drone controller with screen": "пульт управления дроном",
    "field radio station": "полевая радиостанция",
    "whip antenna": "штыревая антенна",
    "radar station": "радиолокационная станция",
    "satellite dish antenna": "спутниковая антенна",
    "gasoline generator": "бензиновый генератор",
    "laptop computer": "ноутбук (КП)",
    "freshly dug soil patch": "пятно свежераскопанной земли",
    "spoil heap of dug-out soil": "куча вынесенного грунта",
    "dugout ventilation pipe": "вентиляционная труба блиндажа",
    "shell crater with scorched earth": "воронка с обожжённой землёй",
    "shrapnel fragments": "осколки снаряда",
    "pile of cut branches": "куча срезанных веток",
    "wilted cut foliage": "увядшая срезанная зелень на маскировке",
    "narrow footpath through bushes": "тропинка через кусты",
    "trampled flattened grass": "примятая трава",
    "extinguished campfire site": "затушенное кострище",
    "grey ash soot patch": "пятно золы/копоти",
    "muzzle blast scorched grass": "задульный конус (выжженная трава)",
    "disturbed snow with tracks": "нарушенный снег со следами",
    "dark melt spots on snow": "тёмные пятна на снегу",
    "sun glint on optics or metal": "блик на оптике или металле",
    "white plastic sheet or bag": "белый полиэтиленовый пакет/плёнка",
    "cigarette pack": "пачка сигарет",
    "food can": "консервная банка",
    "litter pile": "куча мусора",
    "jerry can fuel container": "топливная канистра",
    "discarded tire": "брошенная покрышка",
    "pile of cement bags": "куча мешков с цементом",
    "sand or gravel pile": "куча песка/гравия",
    "rebar steel rods bundle": "пучок арматуры",
    "welded wire mesh": "сварная сетка",
    "roofing felt rolls": "рулоны рубероида",
    "construction debris pile": "куча строительного мусора",
    "military motorcycle": "военный мотоцикл",
    "ATV quad bike": "квадроцикл",
    "snowmobile": "снегоход",
    "pickup truck with mounted gun": "пикап с пулемётом",
    "fuel bowser truck": "топливозаправщик",
    "ambulance vehicle": "санитарная машина",
    "evacuation vehicle": "эвакуационная машина",
    "towed howitzer": "буксируемая гаубица",
    "mortar": "миномёт",
    "mortar baseplate": "опорная плита миномёта",
    "automatic grenade launcher": "автоматический гранатомёт (АГС)",
    "heavy machine gun on tripod": "крупнокалиберный пулемёт на треноге",
    "train car with cargo": "воинский вагон с грузом",
    "armored vehicle on flatbed": "бронетехника на платформе",
    "tarp-covered vehicle on train platform": "техника под брезентом на платформе",
    "stack of railway sleepers": "штабель шпал",
    "field bakery with smoking chimney": "полевая хлебопекарня с дымом",
    "medical tent cluster": "палаточный городок медпункта",
    "dummy tank decoy": "макет танка",
    "dummy artillery piece": "макет орудия",
    "corner radar reflector": "уголковый отражатель",
    "smoke canister": "дымовая шашка",
    "wood-burning field stove": "печь-буржуйка",
}


def ru(class_en):
    """Возвращает русский перевод класса или оригинал, если перевода нет."""
    return CLASSES_RU.get(class_en, class_en)


MILITARY_CLASSES = [
    # ── Бронетехника и авиация ──
    "tank",
    "tank turret in ground",        # вкопанная башня — классика скрытых позиций
    "dug-in artillery",             # окопанная артиллерия
    "armored vehicle",
    "armored personnel carrier",
    "vehicle with cage armor",      # те самые "решётки"/мангалы на технике
    "military truck",
    "military jeep",
    "tanker truck",
    "self-propelled artillery",
    "multiple rocket launcher",
    "anti-aircraft gun",
    "howitzer",
    "missile launcher",
    "military helicopter",
    "military aircraft",
    "quadcopter drone",
    "military boat",
    "inflatable decoy",             # ложные цели — враг обманывает, мы ищем обман

    # ── Личный состав и активность ──
    "soldier",
    "person in camouflage uniform",
    "armed person",
    "person carrying rifle",
    "person with shovel",           # кто-то копает = свежая позиция
    "soldier digging trench",
    "group of soldiers",

    # ── Вооружение, снаряжение, хозяйство ──
    "rifle",
    "machine gun",
    "grenade launcher",
    "anti-tank missile",
    "ammunition box",
    "wooden crate",
    "metal barrel",
    "jerry can",                    # топливные канистры — вечный спутник позиций
    "portable generator",           # генератор: без него ни РЭБ, ни связь
    "field kitchen",                # полевая кухня = люди рядом
    "wooden pallet",

    # ── Антенны, РЭБ, связь ──
    "military radio antenna",
    "radio mast",
    "satellite dish",
    "radar",
    "electronic warfare antenna",
    "communication antenna",

    # ── Укрепления и заграждения ──
    "trench",
    "bunker",
    "dugout entrance",
    "foxhole",
    "barbed wire",
    "barbed wire coil",
    "anti-tank obstacle",
    "dragon teeth obstacle",
    "Czech hedgehog obstacle",
    "concrete block barricade",
    "gabion barrier",               # габионы/HESCO — визитка современных укрепов
    "sandbag wall",
    "checkpoint",
    "watchtower",
    "earth berm",
    "anti-tank ditch",

    # ── Маскировка и укрытия ──
    "camouflage net",
    "camouflaged position",
    "vehicle under net",
    "covered vehicle",
    "military tent",
    "medical tent",
    "command tent",
    "anti-drone net",               # противодронные сети/экраны
    "drone protection cage",
    "metal grille armor",
    "cut branches on ground",       # срезанные ветки = свежая маскировка

    # ── СЛЕДЫ ПРИСУТСТВИЯ (мусор и демаскирующие признаки) ──
    "plastic bottle",
    "metal can",
    "food wrapper",
    "discarded paper",
    "cardboard box",
    "plastic bag",
    "garbage pile",
    "campfire remains",
    "smoke plume",                  # дым: костёр, генератор, подбитая техника
    "dust cloud",                   # пыль от движения техники по грунту
    "tire track",
    "footpath in grass",            # тропинка там, где её "не должно быть"
    "trampled vegetation",
    "disturbed soil",
    "fresh dug dirt",
    "discarded clothing",

    # ── НОВЫЕ КЛАССЫ v2 (личное снаряжение, оружие, мины, дроны, следы) ──
    "soldier in civilian clothing",
    "soldier lying prone",
    "running soldier",
    "soldier carrying military backpack",
    "combat medic with armband",
    "wounded soldier",
    "fallen body",
    "ghillie suit",
    "military helmet",
    "body armor vest",
    "tactical vest with pouches",
    "military backpack",
    "combat tourniquet",
    "rolled bandage",
    "bloody bandage",
    "first aid pouch IFAK",
    "stretcher",
    "battle rifle",
    "carbine",
    "submachine gun",
    "light machine gun",
    "general purpose machine gun",
    "heavy machine gun",
    "anti-materiel rifle",
    "suppressed rifle",
    "underbarrel grenade launcher",
    "telescopic sight",
    "bipod",
    "spent cartridge case",
    "pile of shell casings",
    "spent artillery shell casing",
    "pile of artillery shell casings",
    "spent mortar round tail fin",
    "ammunition magazine",
    "ammo belt",
    "linked ammunition box",
    "ammunition crate",
    "artillery shell",
    "mortar round",
    "hand grenade",
    "anti-tank mine",
    "anti-personnel mine",
    "directional fragmentation mine",
    "bounding mine",
    "tripwire booby trap",
    "RPG-7 grenade launcher",
    "spent RPG launch tube",
    "RPG-18 Mukha launcher",
    "RPG-26 launcher",
    "M72 LAW launcher",
    "AT4 disposable launcher",
    "MRO-A Shmel thermobaric",
    "anti-tank guided missile launcher",
    "ATGM missile in container",
    "MANPADS",
    "FPV drone",
    "fixed-wing drone",
    "reconnaissance drone",
    "drone propeller",
    "drone wreckage",
    "fiber optic spool",
    "thin glinting fiber optic cable",
    "drone antenna",
    "drone controller with screen",
    "field radio station",
    "whip antenna",
    "radar station",
    "satellite dish antenna",
    "gasoline generator",
    "laptop computer",
    "freshly dug soil patch",
    "spoil heap of dug-out soil",
    "dugout ventilation pipe",
    "shell crater with scorched earth",
    "shrapnel fragments",
    "pile of cut branches",
    "wilted cut foliage",
    "narrow footpath through bushes",
    "trampled flattened grass",
    "extinguished campfire site",
    "grey ash soot patch",
    "muzzle blast scorched grass",
    "disturbed snow with tracks",
    "dark melt spots on snow",
    "sun glint on optics or metal",
    "white plastic sheet or bag",
    "cigarette pack",
    "food can",
    "litter pile",
    "jerry can fuel container",
    "discarded tire",
    "pile of cement bags",
    "sand or gravel pile",
    "rebar steel rods bundle",
    "welded wire mesh",
    "roofing felt rolls",
    "construction debris pile",
    "military motorcycle",
    "ATV quad bike",
    "snowmobile",
    "pickup truck with mounted gun",
    "fuel bowser truck",
    "ambulance vehicle",
    "evacuation vehicle",
    "towed howitzer",
    "mortar",
    "mortar baseplate",
    "automatic grenade launcher",
    "heavy machine gun on tripod",
    "train car with cargo",
    "armored vehicle on flatbed",
    "tarp-covered vehicle on train platform",
    "stack of railway sleepers",
    "field bakery with smoking chimney",
    "medical tent cluster",
    "dummy tank decoy",
    "dummy artillery piece",
    "corner radar reflector",
    "smoke canister",
    "wood-burning field stove",
]